services:
  app-router-tracker:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: tgtime-router-tracker
    networks:
      - tgtime-router-tracker-network

networks:
  tgtime-router-tracker-network:
    driver: bridge